### ISSUE TITLE
Error's in line 129 & 63

### ISSUE THREAD

**Issue by Harrsn** [Sl-Sanda-Ru/Py-Fuscate#10]
Below is a photo of the error output of `python3 py_fuscate.py` after following the installation instructions. Please help!
![image](https://user-images.githubusercontent.com/64714607/225468788-5189643c-6252-4216-affc-e0cea4ef7c98.png)

**Comment by Sl-Sanda-Ru** [comment]
i have fixed it mate, update the repo and you'll be fine. Thanks for mentioning the bug
