### ISSUE TITLE
Error in line 120

### ISSUE THREAD

**Issue by Vortex-scripts** [Sl-Sanda-Ru/Py-Fuscate#11]
Running code leaves an error in line 120
"'charmap' codec can't decode byte  0x90 in position 3016: character maps to <undefined>"
![Screenshot 2023-03-28 212848](https://user-images.githubusercontent.com/109775088/228427233-c71a6fad-8d46-4e91-9a59-3ee5cb034172.png)

**Comment by JonJon565** [comment]
I'm aslo getting this bug is there a fix?

**Comment by JonJon565** [comment]
![image](https://user-images.githubusercontent.com/97921266/229186008-07bc8bf3-8a83-403f-9ffb-fa3411eb4a13.png)

**Comment by Vortex-scripts** [comment]
Ohh, makes sense

**Comment by Vortex-scripts** [comment]
I'll try that when I get home, see if it fixes it.

**Comment by Vortex-scripts** [comment]
No, that isn't the issue.
It's still the same error code but it is now in position 2994.
