### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by PandoricGalaxy** [Sl-Sanda-Ru/Py-Fuscate#5]
i ran
`py_fuscate.py -r -i main.py -o main_obf.py -s 100`

it just refreshes the console but doesnt obfuscate the file

**Comment by Sl-Sanda-Ru** [comment]
What is your Python version mate?

**Comment by PandoricGalaxy** [comment]
3.10.4

**Comment by Sl-Sanda-Ru** [comment]
when you execute the script without args do you see the help page?

**Comment by PandoricGalaxy** [comment]
Yes the one that tells me the usage of the tool. Just refreshes into a new look when i run the command

**Comment by Sl-Sanda-Ru** [comment]
rename your input file name 'main.py' to something else your filename conflicts with script's main function I'm pretty sure this will fix your problem

**Comment by PandoricGalaxy** [comment]
> rename your input file name 'main.py' to something else your filename conflicts with script's main function I'm pretty sure this will fix your problem

didnt fix.. i changed name but still does nothing but refresh

**Comment by PandoricGalaxy** [comment]
It's windows 10
