### ISSUE TITLE
Not a obfuscator`

### ISSUE THREAD

**Issue by ImInTheICU** [Sl-Sanda-Ru/Py-Fuscate#6]
This inst a obfuscator, it does not modify origin code it legit packs it

**Comment by Sl-Sanda-Ru** [comment]
Same thing isn't it mate, after packing you can't see the origin code because there isn't a way to unpack

**Comment by ImInTheICU** [comment]
> Same thing isn't it mate, after packing you can't see the origin code because there isn't a way to unpack

This can be uncompiled in seconds,

Obfuscation is modifying the origin code, not stacking it down and down.
