### ISSUE TITLE
De obfuscator

### ISSUE THREAD

**Issue by dhrtlocker** [Sl-Sanda-Ru/Py-Fuscate#7]
Used obfuscator long time ago and now i want to update some code in my python script but lost my source code, dont afford again to hire a developer to recode whole program could you please help me to de-obfuscate my python program..??

Thank you & Regards
Dhrtlocker.

**Comment by Sl-Sanda-Ru** [comment]
Sorry Mate, I haven't found a way to deobfuscate The code.

**Comment by 0x3C50** [comment]
@Sl-Sanda-Ru i just made one https://github.com/0x3C50/nofuscate

**Comment by Sl-Sanda-Ru** [comment]
> @Sl-Sanda-Ru i just made one https://github.com/0x3C50/nofuscate

Great Work Mate ;) Cheers
